### ISSUE TITLE
Different version of the NetLogo Extension API.

### ISSUE THREAD

**Issue by aoguedao** [NetLogo/Shell-Extension#6]
Hi!

First of all thank you so much for this extension, it was the last piece I needed for running some models on a HPC. I'm getting the following warning when I unzip the extension next to my model (I can't use a GUI on the cluster so I can't use the extension manager).

`WARNING: You are attempting to open a NetLogo extension file that was created for a different version of the NetLogo Extension API. (This NetLogo uses Extension API 6.1; the extension uses NetLogo Extension API 6.0.) NetLogo can try to load the extension, but it might not work.`

I know the last commit was years ago but I would love to know if there is any chance to fix this by myself.

Thanks!

**Comment by LaCuneta** [comment]
Hey @aoguedao Thanks for your interest in NetLogo and for your offer to help with the changes.  This extension was updated for the 6.1 API previously, but I see the extension was never posted here as a "release".  That's because it's hosted in the NetLogo extensions library:  https://raw.githubusercontent.com/NetLogo/NetLogo-Libraries/6.1/extensions/shell-1.0.0.zip

It's available in [the extensions manager within NetLogo](https://ccl.northwestern.edu/netlogo/docs/extension-manager.html), but if you need to add it to an HPC install you can just use that zip I linked above.  

I'll go ahead and add the zip file as a release here as well, just to try to prevent any future confusion.
